// Full-length source documents for a subset of investigation actions —
// interview transcripts, cell-site/ANPR analyst reports, and procedural
// documents — ported (close to verbatim) from Reference/case-content's
// hollenbourne-interviews.md, hollenbourne-cell-site-data.md, and
// hollenbourne-procedural-documents.md.
//
// This exists because lib/evidence-catalog.ts's buildActionEvidence()
// otherwise gives every action-derived exhibit only its own action's short
// outcome paragraph as the "full text" — for these actions, much richer
// source material already existed in Reference/ but had never been ported
// into the Case Log itself, so "read in full" showed nothing beyond the
// one-paragraph summary already visible on the action card. Only actions
// with a genuine fuller document behind them are listed here; the rest
// correctly fall back to their outcome text in evidence-catalog.ts.
//
// Where the source material used "DS R. Fenwick" (the 2023 Porterhouse
// interviews in hollenbourne-interviews.md), it's corrected to DS H. Ferris
// throughout — see CLAUDE.md's "Corrected" note: Ferris conducts every
// interview across the whole case, and Fenwick was a naming drift in an
// earlier draft, not a second detective.

import type { EvidenceBodySection } from "./evidence-catalog";

export const ACTION_EVIDENCE_BODY: Record<string, EvidenceBodySection[]> = {
  // -----------------------------------------------------------------------
  // Interviews — hollenbourne-interviews.md
  // -----------------------------------------------------------------------
  "pull-interview-burgess-mason": [
    {
      heading: "Voluntary interview under caution — 16 October 2019",
      paragraphs: [
        "Interviewee: Martin Burgess. Location: Hollenbourne Police Station, Interview Room 2. Present: DS H. Ferris (interviewing officer), DC R. Osei (second officer), M. Burgess. Mr Burgess was offered a solicitor and declined. Time commenced: 10:14.",
        "FERRIS: This interview is being recorded. Mr Burgess, you're not under arrest and you're free to leave at any time, but I do need to caution you. You do not have to say anything, but it may harm your defence if you do not mention, when questioned, something which you later rely on in court. Anything you do say may be given in evidence. Do you understand that?",
        "BURGESS: Yeah. I understand.",
        "FERRIS: And you've been offered the chance to have a solicitor here with you today, and you've said you don't want one. Is that right?",
        "BURGESS: That's right. I've got nothing to hide, I just want to help if I can.",
        "FERRIS: Alright. Before we get into today, can you tell us a bit about yourself? What do you do for work?",
        "BURGESS: Gas engineer. Boiler technician, really — servicing, repairs, the odd install.",
        "FERRIS: How long have you been doing that?",
        "BURGESS: Coming up ten years now. Did my apprenticeship, been with the company about six of those.",
        "FERRIS: And Hollenbourne's part of your regular patch?",
        "BURGESS: Yeah, on and off. Bit of everywhere round here, really — wherever the jobs come in.",
        "FERRIS: I want to ask you about something on our system, if that's alright. There's a matter from a few years back — you were charged in relation to a death, manslaughter, and it didn't proceed to trial. Can you tell me about that?",
        "BURGESS: [pause] That's — yeah. Long time ago now. Nightclub, things kicked off, I wasn't the only one involved. It never went anywhere because there wasn't the evidence, because I didn't do what they said I did. I don't love talking about it, if I'm honest. It was dealt with.",
        "FERRIS: That's fine, we don't need to go over it again. Whereabouts do you live these days?",
        "BURGESS: Grays. Small flat, on my own.",
        "FERRIS: Alright. So in your own words, can you tell us why you're here today?",
        "BURGESS: Yeah, so I saw it in the paper — about Geoff. Mr Mason. And I was actually going to come in myself, because I was round his the day it happened. So I thought, better I come and say something than you lot find out some other way and think I was hiding.",
        "FERRIS: That's helpful, thank you. Can you talk us through your visit to the property?",
        "BURGESS: Yeah. So I had a boiler service booked in, that would've been early afternoon. Got there about half two. Geoff answered the door, let me in, showed me through to where the boiler is, in the airing cupboard.",
        "FERRIS: Okay. Go on.",
        "BURGESS: So I got started on the service. He was around, in and out, we had a chat while I was working — he was telling me a bit about the area, how it's changed over the years. Nice bloke. Bit lonely, I think, if I'm honest, he seemed glad of the company.",
        "FERRIS: What time did you finish the service?",
        "BURGESS: About quarter to four. I signed it off, wrote it up.",
        "FERRIS: And what time did you leave the property?",
        "BURGESS: Round about four. Maybe just before.",
        "FERRIS: Before we come back to that — did Geoff say anything else that stood out to you? Anything that worried you at all?",
        "BURGESS: Yeah, actually — now you mention it, he did seem a bit off. I asked him if he was alright and he sort of brushed it off, said something like the neighbourhood wasn't what it used to be. Didn't think much of it at the time.",
        "FERRIS: Okay. I want to go back to the timings now, if that's alright, Martin. You've said you left the property around four. Our records — your company's own vehicle tracking — has your van leaving that road at 4:45pm. That's the best part of an hour after you say the job finished. Can you help me understand that gap?",
        "BURGESS: [pause] Right, yeah. Okay, so — a couple of things, actually. I hadn't had my lunch, I'd been going all day, so I drove round the corner after I left Geoff's, and just sat in the van for half an hour or so. Had a sandwich, had the radio on. Didn't think it was worth mentioning, it's not exactly interesting.",
        "FERRIS: That would take us to about half four. There's still a gap.",
        "BURGESS: Yeah, no — sorry, and the other thing is, thinking about it properly now — I didn't leave straight at quarter to four like I said. I'd finished the actual service, but Geoff wanted a chat, like I said, about the area, and he seemed a bit off, so I stayed on a bit. Ten, fifteen minutes, maybe. So it would've been closer to four when I actually left the house. And then the lunch after that.",
        "FERRIS: So to be clear — service finished 3:45, but you're now saying you left the property closer to four, then drove round the corner for lunch until about half four.",
        "BURGESS: Yeah. That's — yeah, that sounds right.",
        "FERRIS: Alright. Martin, I want to ask you something directly, and I want you to think carefully before you answer. Did you have any involvement in the death of Geoff Mason?",
        "BURGESS: No. Absolutely not, no.",
        "FERRIS: Do you have any idea who did it?",
        "BURGESS: No, I don't. All I can think is that it's one of those estates, you know? Drugs and that. Kids...",
        "FERRIS: Could you be more specific?",
        "BURGESS: I mean you're always hearing about Hollenbourne and county lines stuff. People kicking people out of their houses and selling drugs from there. You know more about it than me.",
        "FERRIS: Did you see anything that made you think that Geoff was involved in that?",
        "BURGESS: No, not really, but like I said he seemed stressed about something. I wondered if it was that.",
        "FERRIS: Alright, Martin. I don't have any further questions for you at this time. Thank you for coming in.",
        "Time concluded: 11:03. No further action taken at this time.",
      ],
    },
  ],

  "pull-interview-wooley": [
    {
      heading: "Interview 1 — 7 January 2022 (terminated early)",
      paragraphs: [
        "Interviewee: Nigel Wooley. Interview following arrest. Location: Hollenbourne Police Station, Interview Room 1. Present: DS H. Ferris (interviewing officer), DC L. Marsh (second officer), N. Wooley. Mr Wooley was offered a solicitor and declined. Time commenced: 09:20.",
        "FERRIS: This interview is being recorded. Mr Wooley, you've been arrested in connection with the death of Susan Wooley, and I need to caution you. You do not have to say anything, but it may harm your defence if you do not mention, when questioned, something which you later rely on in court. Anything you do say may be given in evidence. Do you understand?",
        "WOOLEY: Yeah. I understand.",
        "FERRIS: Before we go any further — are you aware of what's happened to Susan?",
        "WOOLEY: Yeah. My daughter rang me last night, told me. I still can't really take it in, to be honest.",
        "FERRIS: I'm sorry for your loss. I do need to ask you some questions today, and some of them will be difficult, but we'll take our time. Alright? Can you tell me what you do for work?",
        "WOOLEY: Surveyor. Residential, mostly — been with the same firm years now. Coming up thirty years.",
        "FERRIS: Can you tell me a bit about your relationship with Susan? Wherever you want to start.",
        "WOOLEY: We met in 2012 — mutual friend, Nadia, introduced us. Hit it off pretty quick, actually. Got married in '14. Good years, those. She was easy to be around. Funny. Worked at St Martin's, teaching assistant, she loved that job.",
        "FERRIS: And things changed at some point?",
        "WOOLEY: Yeah. Lockdown didn't help anyone, did it. Stuck in the house, both of us on edge. She ended it in the end — 2021. I moved out to Featherton.",
        "FERRIS: You were convicted of stalking her last year and given a suspended sentence with a restraining order. Can you talk me through that?",
        "WOOLEY: [defensive] That got blown up a lot more than it needed to be, if I'm honest. I sent some messages, I turned up a couple of times because I wanted to talk to her properly, that's all it ever was. Court gave me a suspended sentence, didn't they — not prison. That tells you something about how serious it actually was, doesn't it.",
        "FERRIS: Can you talk me through your evening on the 6th of January? From when you got home.",
        "WOOLEY: Yeah, so — got in from work about five, sorted some dinner, had that about six. Watched a bit of telly, football was on I think. Didn't take Missy out again that evening — she'd already had a walk earlier, over the rec. Just stayed in, really. Bed about eleven.",
        "FERRIS: So you didn't leave the house at all that evening?",
        "WOOLEY: No. Not that I remember, no.",
        "FERRIS: Your phone was at your home address until about quarter past nine, and then nothing for a couple of hours. Where was it?",
        "WOOLEY: Must've left it charging in the kitchen. I do that sometimes, forget to carry it round with me.",
        "FERRIS: [pause] We have CCTV footage from that evening. It shows a man matching your description, walking a dog matching your dog's description, on the footpath along Hollen Marsh, at 9:47pm.",
        "WOOLEY: [immediately] That's not — that can't be me. I told you, I was in all night.",
        "FERRIS: The footage is fairly clear, Nigel.",
        "WOOLEY: Well it's not me, then. I don't know what to tell you. Loads of people walk dogs round there, it's not exactly—",
        "FERRIS: The coat on the man in the footage matches one we recovered from your flat this morning. Green, waxed, tear on the left sleeve.",
        "WOOLEY: [pause] ...I've got a coat like that. Doesn't mean—",
        "FERRIS: Nigel.",
        "WOOLEY: [long pause, deflating] ...Alright. Fine. I might have popped out for a bit. It's not what you think, though. I forgot, didn't I. It wasn't a big thing, I just needed some air.",
        "FERRIS: Hollen Marsh is inside the area your order covers.",
        "WOOLEY: [flustered] It's a public path! I wasn't anywhere near her house, I never even — I haven't done anything wrong here, not really. I walked the dog somewhere I shouldn't have. That's not exactly a crime, is it.",
        "FERRIS: We've also recovered a DNA profile matching you from inside the property.",
        "WOOLEY: We were married for years. Course there's — that doesn't mean anything, that could be from years back.",
        "FERRIS: Nigel, did you have any involvement in Susan's death?",
        "WOOLEY: No. God, no. I would never — no.",
        "FERRIS: You understand how the timing looks. The order, the marsh, the phone left behind, lying to me about all of it two minutes ago.",
        "WOOLEY: [rattled] Look — I think I want to speak to someone. A solicitor. Before I say anything else.",
        "FERRIS: That's your right. This interview is suspended at 10:14 to allow Mr Wooley to obtain legal advice.",
      ],
    },
    {
      heading: "Interview 2 — 7 January 2022, resumed (with legal representation)",
      paragraphs: [
        "Present: DS H. Ferris (interviewing officer), DC L. Marsh (second officer), N. Wooley, R. Okafor (solicitor). Time commenced: 13:40.",
        "FERRIS: This interview is being recorded, continuing under caution from this morning. Mr Wooley, you now have your solicitor present.",
        "OKAFOR: My client would like to clarify his earlier account. Go ahead, Nigel.",
        "WOOLEY: Yeah. I want to explain properly what I was doing that night, because I wasn't straight with you before, and I know that. I'd heard — through someone, doesn't matter who — that Susan had started seeing someone. And I couldn't leave it alone. I know exactly how that sounds.",
        "FERRIS: I want to go through that evening properly this time. Can you talk me through it from when you left your flat?",
        "WOOLEY: Yeah. Left about half nine, twenty to ten maybe. Walked down through Featherton, out onto the marsh path — it's fifteen, twenty minutes that way with the dog. Got to the spot where the path comes out near her road about quarter to ten. Stood there a bit. You can see the back of a couple of houses from that spot. Hers is one of them.",
        "FERRIS: What did you see?",
        "WOOLEY: Not much, if I'm honest. House was dark. No lights on that I could see, kitchen at the back, nothing. I remember thinking that was odd, actually — she wasn't one to sit in the dark, Susan. Always had something on, telly or the lights at least.",
        "FERRIS: You noticed the house was dark, thought it was unusual, and did nothing about it.",
        "WOOLEY: What was I supposed to do — knock on the door? I wasn't meant to be anywhere near there in the first place.",
        "FERRIS: How long were you there?",
        "WOOLEY: Five minutes. Ten at most. Walked back the same way. Home by about half ten. Never past that spot on the path. I know how it sounds, but that's the truth of it.",
        "FERRIS: This morning you told me twice you hadn't left the house at all, and only admitted otherwise once we showed you the coat. Now you're giving me a full account with a clear reason behind it.",
        "OKAFOR: My client was in shock this morning, Detective Sergeant, having just been arrested in connection with his ex-wife's death. He's had the chance to speak with me and wants to be straightforward about the breach — which he accepts, fully — while being clear that it's the only thing he did.",
        "WOOLEY: I broke my order. I know that, and I'll take whatever's coming for it. But I didn't touch Susan. I didn't go near her.",
        "FERRIS: You understand how it looks, Nigel. History with Susan, a breach on the night in question, no alibi for the gap, DNA in the property.",
        "WOOLEY: I understand exactly how it looks. That doesn't make it true.",
        "FERRIS: Alright. I don't have any further questions at this time.",
        "Time concluded: 14:11. Mr Wooley was released on police bail pending further enquiries.",
      ],
    },
  ],

  "pull-interview-haddad": [
    {
      heading: "Interview following arrest — 2 June 2023",
      paragraphs: [
        "Interviewee: Khalid Haddad. Location: Hollenbourne Police Station, Interview Room 2. Present: DS H. Ferris (interviewing officer), DC L. Marsh (second officer), K. Haddad, S. Adeyemi (solicitor). Time commenced: 11:05.",
        "FERRIS: This interview is being recorded. Mr Haddad, you've been arrested in connection with the death of Carl Porterhouse, and I need to caution you. You do not have to say anything, but it may harm your defence if you do not mention, when questioned, something which you later rely on in court. Anything you do say may be given in evidence. Do you understand?",
        "HADDAD: Yes.",
        "ADEYEMI: My client understands the caution and has been advised on his right to silence.",
        "FERRIS: Noted. Khalid, can you talk me through your evening on the 29th of May?",
        "HADDAD: No comment.",
        "FERRIS: What were you wearing that night?",
        "HADDAD: No comment.",
        "FERRIS: What time did your shift start? What time did you finish, and go home?",
        "HADDAD: No comment.",
        "FERRIS: Did you make any stops that evening that weren't part of a delivery?",
        "HADDAD: No comment.",
        "FERRIS: I want to ask specifically about the period between around 9 and half past ten that evening. Can you tell me where you were?",
        "HADDAD: No comment.",
        "FERRIS: [pause] Khalid, I'll be straightforward with you. We have your delivery app data. It shows no active job between 9:10 and 9:55 that night. Your phone was stationary for that whole period, on a road in Boresfield. Do you want to tell me why?",
        "HADDAD: No comment.",
        "FERRIS: This is a murder investigation. If there's an innocent explanation for where you were, this is the time to give it. I have to remind you that if you don't mention something now and later rely on it in court, that silence can be used against you.",
        "HADDAD: [pause] No comment.",
        "FERRIS: Alright. I don't have any further questions at this time.",
        "Time concluded: 11:31. Mr Haddad was released on police bail pending further enquiries.",
      ],
    },
  ],

  "pull-interview-swayne": [
    {
      heading: "Interview following arrest — 3 June 2023",
      paragraphs: [
        "Interviewee: Colin Swayne. Location: Hollenbourne Police Station, Interview Room 1. Present: DS H. Ferris (interviewing officer), DC L. Marsh (second officer), C. Swayne. Mr Swayne was offered a solicitor and declined. Time commenced: 14:02.",
        "FERRIS: This interview is being recorded. Colin, you've been arrested in connection with the death of Carl Porterhouse, and I need to caution you. You do not have to say anything, but it may harm your defence if you do not mention, when questioned, something which you later rely on in court. Anything you do say may be given in evidence. Do you understand?",
        "SWAYNE: Yeah. That's fine.",
        "FERRIS: Before we start — I can see some bruising, your face, your arms. You've been seen by a medic? I've also got a note on file about a diagnosed brain injury. I want to check what that means for today?",
        "SWAYNE: Erm yeah, I got hit on the head a while back, sometimes go a bit funny, can't remember stuff.",
        "FERRIS: Ok, thank you. So if anything doesn't make sense, or you need a break, just say so. We're not in a rush today. Also if there is something you don't remember just say so, don't guess. We just want the truth of what happened here.",
        "SWAYNE: Okay.",
        "FERRIS: Can you tell me a bit about yourself, Colin? How long have you lived round Boresfield?",
        "SWAYNE: Grew up round here, near the old Critchley works. [pause] Hard, I suppose. My dad died when I was young. Nine. My mum did her best after, with the three of us, but it wore her down over the years.",
        "FERRIS: I'm sorry to hear that. Are you close with your family these days?",
        "SWAYNE: Not really, I still see my younger brother. My mum went in 2018. [shrugs] Cancer. Long time coming, that one. I looked after her, best I could, at the end.",
        "FERRIS: Look, I know you've got a bit of a history and I don't want to go over old ground unnecessarily but, just briefly, can I ask about your record?",
        "SWAYNE: It's alright. I know what's on there. Drugs mostly. Started young. Stopped for a bit after the second prison sentence but started using again after my mum. Crack. Brown when I can get it. Whatever's about, really. Since I was a teenager really. Tried a couple of times to get help. Did courses in prison and then when I got out. Never stuck.",
        "FERRIS: Just so we understand what a day looks like for you. Can you tell me what you did the morning of the 29th?",
        "SWAYNE: [thinks] Slept late. Watched telly a bit. Went to the shop for milk and baccy, I think. Normal sort of day.",
        "FERRIS: And the afternoon?",
        "SWAYNE: I was in the flat. Started using. Probably 1 or 2 o'clock, I get up late. And that would've been crack, and I had some beers.",
        "FERRIS: Was anyone else there?",
        "SWAYNE: No.",
        "FERRIS: Ok, do you remember what you were wearing?",
        "SWAYNE: Not really, probably this [gestures to his current outfit] — blue tracksuit bottoms and a white and blue sweater. Probably put a coat on to go to the shops. Same dark blue puffer jacket I've brought today. It's the only one I've got.",
        "FERRIS: Ok, so did anything change in the evening. Did you go out again at all?",
        "SWAYNE: No, I was in all night. Didn't go anywhere.",
        "FERRIS: You're sure about that. We've got a witness who saw you on Bamford Street at around 8:30.",
        "SWAYNE: They're wrong. I didn't go out.",
        "FERRIS: They described your clothes and appearance that day pretty accurately. Are you sure you didn't go out? Can I ask you to think back carefully?",
        "SWAYNE: [silence] [pause] I suppose... I was probably going for a walk.",
        "FERRIS: Okay, this witness says they saw you entering number 42 on Bamford Street. Carl Porterhouse's flat.",
        "SWAYNE: [silence] [pause] I don't remember going out. But I know that Carl owed me some money so maybe I went round to grab it?",
        "FERRIS: What was your relationship with Carl?",
        "SWAYNE: Acquaintance. Dunno, not long, maybe a year? Not really [well]. He'd come round the house sometimes. We'd have a chat. He's sort of my generation, lived in the area too, so we got on ok. He wanted a bit of cash for crack or whatever and I said he could have it. He seemed alright.",
        "FERRIS: Ok, and on the 29th you went to his house and got your money back.",
        "SWAYNE: Yeah. [pause] I think so, I dunno, like I said I don't remember going out. If I was just getting my money probably not long. We might have had a chat.",
        "FERRIS: We've had forensic results back from the property. There's a lot of you in that flat, Colin — not the kind of trace you'd leave dropping something at the door and walking off.",
        "SWAYNE: [silence, looks down] Can I use the loo?",
        "FERRIS: Of course, let's take a break for a bit.",
        "Interview suspended 14:47 for a break at Mr Swayne's request. Resumed 15:01.",
        "FERRIS: Ok, so you're happy to continue? Is there anything else you remember about the time you went to visit Carl's house?",
        "SWAYNE: [quiet] We were using together. Me and Carl. I stayed a bit. Longer than ten minutes. Dunno. Hour, maybe. Bit more.",
        "FERRIS: What sort of mood was Carl in?",
        "SWAYNE: Good mood. We were just talking. Music, mostly. We grew up in the same scene so we like similar stuff.",
        "FERRIS: Ok, thank you Colin. I need to tell you what the examination of Carl's body showed. He had injuries to his head, and bruising to his arms and body, that aren't easy to explain from one person losing their temper with him. There's evidence more than one person was involved.",
        "SWAYNE: [silence]",
        "FERRIS: Did something happen between the two of you? An argument, maybe, about the money?",
        "SWAYNE: No. Nothing like that. We were fine.",
        "FERRIS: Did you get the money you were owed?",
        "SWAYNE: [pause] Nah. Don't think so. Can't remember properly.",
        "FERRIS: So you went round for money, and came away without it.",
        "SWAYNE: Maybe he didn't have it. I dunno.",
        "FERRIS: Did that make you angry?",
        "SWAYNE: No. Nothing like that. Wasn't even much money.",
        "FERRIS: So nobody else came to the flat while you were there.",
        "SWAYNE: [pause] I don't know. Said already, some of it's not there for me.",
        "FERRIS: I understand that, Colin. But I think you know more than you're telling me. Was there anyone else in that flat with you and Carl that evening?",
        "SWAYNE: [doesn't answer, looks at the table] [long pause] Can't tell you what I don't remember. You said don't guess. I'm not guessing.",
        "FERRIS: [pause] That's fair, Colin, and I meant that. But this isn't the same as this morning, not remembering what you had for breakfast. This is what happened to your friend.",
        "SWAYNE: [silence]",
        "FERRIS: Colin, I want to be straight with you. If there's an explanation for this — if someone else did this and you got caught up in it — this is your chance to say so. You've not had an easy run of things. We don't want to see you go down for something you didn't do.",
        "SWAYNE: [long silence; hands visibly shaking; doesn't look up] [very quiet] Can't say.",
        "FERRIS: Can't, or won't?",
        "SWAYNE: [barely audible] Doesn't matter which. Same thing, where I live.",
        "FERRIS: [pause] Okay. I'm not going to push you on that right now.",
        "SWAYNE: [quiet] Sorry.",
        "FERRIS: Nothing to be sorry for. Is there anything else about that evening you're able to tell me?",
        "SWAYNE: No. Not that I can say.",
        "FERRIS: Alright. We'll leave it there for now.",
        "Time concluded: 15:52. Mr Swayne was released under investigation pending further enquiries. His injuries were photographed and logged. He declined a referral to victim support services.",
      ],
    },
  ],

  "reint-swayne": [
    {
      heading: "Further interview (voluntary) — case review, 2025 (all four deaths)",
      paragraphs: [
        "Interviewee: Colin Swayne. Officers: DS H. Ferris (interviewing), DC L. Marsh (second officer). Mr Swayne was offered a solicitor and declined.",
        "FERRIS: Thanks for coming in again, Colin. Last time we spoke we talked about the death of Carl Porterhouse, and we're very grateful for your help there. We might pick up on that again today, but really we're going over a few cases from around the Boresfield area. Really, we're interviewing you today as someone who knows the area well. Before I start — I've got a note on file about your head injury. Same as always: if anything's not clear, or you need a break, just say so.",
        "SWAYNE: Yeah, I know the drill.",
        "FERRIS: Geoff Mason. Does that name mean anything to you?",
        "SWAYNE: No, I don't know him.",
        "FERRIS: Geoff Mason was an old gentleman who lived on the street backing onto the marsh — nice garden, kept it well? He'd been on the estate for years.",
        "SWAYNE: Oh, yeah, I know the place. I haven't seen him in a while, I assumed he'd died.",
        "FERRIS: He was murdered in October 2019.",
        "SWAYNE: Jesus. [pause] I hadn't heard that. What happened? [pause] I didn't do it. I'm just finding out about it. It's horrible.",
        "FERRIS: Okay, and we're not accusing you today, Colin, we're just trying to chase a few leads and rule people out of our investigations, so anything you can tell us about your whereabouts on the 8th of October would be really helpful.",
        "SWAYNE: I've got no idea where I was. Look, I don't go out much. I go to the shops, I've got a few mates round the estate, but I'm probably at my flat most of the time.",
        "FERRIS: Geoff was killed on the Tuesday, the 8th — though with a body left outdoors that long, we can't pin the time down more precisely than that. Does that help at all? Do you ever go down to the marshes?",
        "SWAYNE: Not really. Depressing place. [pause] Look, I would have been in the area most likely, but I can't tell you anything apart from that. I didn't know the guy and I didn't kill him.",
        "FERRIS: Do you know if anyone had anything against him? Anyone who might have killed him?",
        "SWAYNE: No. [pause] The kids pestered him, I think. Some dealers came up to him, tried to use his house to sell out of. He told them to fuck off. That was it. Just heard it.",
        "FERRIS: Okay — so are you sure you didn't know him better than you've said?",
        "SWAYNE: I've told you, I knew who he was, I didn't know his name. Christ, I didn't even know he'd been killed! You hear stuff like that, I don't know if it's true, but you asked if he had any problems and that's all I could think of.",
        "FERRIS: Did you know Susan Wooley?",
        "SWAYNE: [pause, quieter] Yeah. I knew Susan. Food bank. At the church. Went through a bad patch a while back, had to use it pretty regular for a stretch. She used to help run it. [thinks] Year or two, on and off. Look, I don't know what you're getting at here. I ain't killed anyone, I've got no idea why you're asking me about this. You know my record, I'm not a killer, I'm not a violent person. I've got my problems, but I'm just trying to keep going and keep to myself.",
        "FERRIS: Colin, we're not saying you have. You've lived in the area for a while. We know about your past, and we know a little bit about your present. We're not here for that. We just want to see if there's anything you've seen or know about which could help us with these cases. Is that alright?",
        "SWAYNE: [long pause] Yeah. Suppose it has to be.",
        "FERRIS: What was she like? Susan.",
        "SWAYNE: [long pause] Kind. Properly kind, not just doing her bit and moving on to the next person. Remembered your name. Asked how you were and actually waited to hear the answer. I'm not really one for church stuff, all that — makes me uncomfortable, if I'm honest, always feels like there's a catch somewhere. She wasn't like that, though. She just was kind, plain and simple. Didn't need a reason.",
        "FERRIS: That sounds like it mattered to you.",
        "SWAYNE: [quiet] It did. [pause] It knocked me, when I heard what happened to her. More than I'd have expected, if I'm honest with myself. Wasn't like we were close or anything. Just — she was one of the only people who never looked at me like I was a problem to be dealt with.",
        "FERRIS: Do you remember anything about the day she died? January 2022.",
        "SWAYNE: No. Same as with Geoff — can't give you anything solid on that. Wish I could, for her sake. Erm, probably at the food bank. I dunno. January? I probably went a couple times that month. I assume she was there.",
        "FERRIS: Susan lived on Harrison Road. That's not far from your flat. Is there any reason you would ever go along that street?",
        "SWAYNE: Only to go to the shop. I didn't know her address. I never went to her house or anything. I knew she lived on that street. I don't remember. Like I said, I don't really do a lot. If I was near there it would have just been to go to the Londis.",
        "FERRIS: Okay — and as before, do you know of any reason why someone would want to harm Susan?",
        "SWAYNE: None at all. She was a lovely woman. Makes no sense to me. Still doesn't. People obviously talked about her ex. But you spoke to him already, didn't you? I don't know. I didn't know about her life. I just saw her at the church.",
        "FERRIS: Carl Porterhouse — I know we've already been through this.",
        "SWAYNE: I've got nothing else to say about that. After all I went through last time, I'd expect to be in the clink by now if you had anything on me.",
        "FERRIS: Well, that case is still ongoing, Colin.",
        "SWAYNE: You think it's linked to the others? Is that what you're saying?",
        "FERRIS: You're here of your own volition, Colin, so if you don't want to talk about it then that's totally up to you. You're right that we didn't charge you for Carl's murder, but I think you haven't told me everything you know there, and I don't want you to think that we're not still interested in finding out what happened.",
        "SWAYNE: I don't want to talk about that, and if it's okay, I'm going to go now.",
        "FERRIS: You're free to go whenever you like, Colin, I appreciate your time and your help. Before you go, can I just ask about Sara Butt? As I said, you're not being held here.",
        "SWAYNE: [pause] Didn't know her at all. Never met her, far as I'm aware. Young, wasn't she?",
        "FERRIS: That's right. As before, do you know where you were on the 22nd?",
        "SWAYNE: Just in the flat.",
        "FERRIS: This was just a few months ago, Colin — can I ask you to think a bit more carefully about it? This was a Thursday night. Do you ever make plans on a Thursday night?",
        "SWAYNE: No, not really. I used to go to the pub sometimes, but not really anymore. What happened with Carl. People got ideas. [pause]",
        "FERRIS: Okay, well, let's stick with Sara. So you didn't go out that evening.",
        "SWAYNE: I might have been down at Hol's place. Holly Creagan. She's a mate. Sometimes we have a drink and whatever.",
        "FERRIS: Do you think you were there on the Thursday, the 22nd?",
        "SWAYNE: I don't know, maybe. If I was out, I'd have been there.",
        "FERRIS: Where does she live?",
        "SWAYNE: Folkestone Road. [pause] I suppose, yeah, near the marshes.",
        "FERRIS: And she would be able to confirm that you were with her?",
        "SWAYNE: Maybe, I dunno. Look, to be honest, if we get together we're probably using together, so I dunno. If I was there then she'd probably know, but like I said, I could have just been in the flat.",
        "FERRIS: Thank you, Colin. That's everything for today.",
        "Time concluded: not specified. No further action taken.",
      ],
    },
  ],

  "haddad-wooley-further-interview": [
    {
      heading: "Further interview (voluntary) — Wooley case, 2025",
      paragraphs: [
        "Interviewee: Khalid Haddad. Officers: DS H. Ferris (interviewing), DC L. Marsh (second officer). Present: S. Adeyemi (solicitor). Time commenced: 10:15.",
        "FERRIS: Thanks for coming in, Khalid. This isn't an arrest, and you're not under caution today — this is a voluntary follow-up, part of some wider work we're doing. I want to start by asking you about a date, the 6th of January 2022. Does that mean anything to you?",
        "HADDAD: [pause] Not really, no.",
        "FERRIS: Do you remember your general routine round then? Were you doing deliveries at that time too?",
        "HADDAD: [thinks] Uhm, yeah. Yeah I was.",
        "FERRIS: So we have some data on your route on that day and it shows you passing through the Boresfield area that evening, does that make sense?",
        "HADDAD: [pause] I go through there most days, so yeah. Probably. No. I can't remember it.",
        "FERRIS: Ok, so perhaps it would be helpful to go through your routine at that time in your life. So you work quite late right? So what sort of time do you normally get up?",
        "HADDAD: Normally around 11, 11:30. Have breakfast, chill with my family. Do stuff around the house. Depends, sometimes I go out and see mates, go to the shops. Sometimes I do some other work at my mates' dad's café. Ilford mostly. Dagenham, Walthamstow. Just in the kitchen, bit of food prep, washing up, cleaning for extra money. I want to do more food stuff.",
        "FERRIS: And so on those days, will you still do deliveries in the evening and at night?",
        "HADDAD: Yeah normally. I look at the app around 5 or 6 when orders are coming in. Deliveroo and Uber. Depends on the day. Sometimes 1 in the morning, on weekends its 2 or 3. Yeah basically east London and south Essex. I go where the orders are so you can be somewhere quite far out sometimes.",
        "FERRIS: Okay, but you say Hollenbourne is quite a frequent location for pickups and deliveries.",
        "HADDAD: Yeah its busier now that the new estates there. Yeah and the north part. But also the south part too, like where Chertsey road is. I don't go to Critchley too much.",
        "FERRIS: So on the 6th of January, we have you in the area at around 6pm. What's a bit more specific is a stop that doesn't match anything on your delivery log for that evening — a few minutes, off the route you were logged as running. How common is that?",
        "HADDAD: [pause] I take breaks sometimes, wait for orders. So yeah, it's normal.",
        "FERRIS: Can you tell me anything more about where you might have stopped on that night of the 6th?",
        "HADDAD: No, I don't remember. It was a while ago. What's it saying I did?",
        "FERRIS: We have you on the northern end of Marsh Road at 18:05. Comparing that with the app data from Deliveroo, you made a delivery on Chertsey Road at 17:55 but then move towards the Marsh Road area later. We have you moving back onto Chertsey Road at 18:15 so can you help us understand that stop?",
        "HADDAD: What's this about though? If you thought I did that Porterhouse geezer you'd have charged me. So what's this about?",
        "ADEYEMI: This is probably a good time to remind my client that he is here voluntarily and doesn't need to answer any questions that he doesn't want to.",
        "FERRIS: Well we're looking at both cases and a few others but I can't say more than that. I want to be straight with you on one thing. A woman was murdered that evening, not far from where that gap is, and not far from where you were. I'm not saying you had anything to do with that but perhaps you saw something that could help us and at least rule you out of the investigation. So you don't have to say anything, you're free to go whenever you like but I think it would help a lot if you could remember what it was you were doing there.",
        "HADDAD: [silence, doesn't respond]",
        "FERRIS: Is there anything about that period you'd rather not go into?",
        "HADDAD: [quiet] Yeah.",
        "FERRIS: Look, we are talking to you today about a murder. You may even have heard about it. We are not concerned with anything else. I know it can be scary or embarrassing, and I know you have some things on your record which you may not be comfortable with talking about, I don't know. Only you know. So help us understand, we are only concerned here with the death of Susan Wooley.",
        "HADDAD: [silence]",
        "FERRIS: Can I ask you something directly? Whatever this is — is it something to do with Susan Wooley's death?",
        "HADDAD: No!",
        "FERRIS: Then I want to be clear with you, Khalid. I'm not interested in anything minor, anything old, anything that's got nothing to do with this case. If it's something small, something you're embarrassed about — that's not what I'm here for. What I actually need is an explanation for the gap. That's all.",
        "HADDAD: [long pause, glances at Adeyemi] [quiet] I don't know if I believe that it just stops there, though. It never has before.",
        "FERRIS: I can't make promises about things outside this case. What I can tell you is this interview is about Susan Wooley, and nothing else. Whatever you tell me about that gap, if it's got nothing to do with her, that's exactly where it stays.",
        "HADDAD: [very long pause] ...Okay. Okay, I'll explain it. There's people from years back. Before all that stuff with the police when I was younger — you have that on file. I promised my mum I was done with all that. And I have been, mostly. But every now and then someone from back then asks for something small. A pickup, a drop-off. Nothing serious. I know how that sounds.",
        "FERRIS: Go on.",
        "HADDAD: That day — if it's what you're saying — it would've been something like that. Someone asking me to grab something on my way through, since I was already driving that way anyway. I wouldn't have thought twice about it at the time. It's not like it is now, wasn't planned, wasn't a regular thing back then. Just — someone knew I drove that patch, asked a favour.",
        "FERRIS: Can you tell me who?",
        "HADDAD: [pause] No. Look, its about your case so I'd rather not say. It's nothing big.",
        "FERRIS: Ok but help me understand a bit more about what it was you were doing. At the moment we just have that you made a stop and it was related to your previous convictions which were drug related. Was it something to do with that?",
        "HADDAD: [pause] Yeah. I was picking something up and dropping it in Featherton. I dunno the guy I gave it to. I don't wanna say anything more. I don't know what I was dropping off anyway.",
        "FERRIS: Okay, thank you Khalid, I appreciate you saying that. Did you see anything, or anyone, unusual that evening? Anything at all?",
        "HADDAD: No. Genuinely, no. It was a normal evening. I wouldn't even remember it at all if it wasn't for this. Man, everyone looks suspicious in those ends. I didn't see anything weird though.",
        "FERRIS: Thank you, Khalid. That's genuinely helpful. I don't have anything further today.",
        "HADDAD: [quiet] Does this go on my file? The favour thing?",
        "FERRIS: It'll be noted as part of this interview. I can't tell you more than that.",
        "HADDAD: [pause] Okay. Fair enough.",
        "FERRIS: You've done the right thing though Khalid. You don't want us asking questions, especially with the evidence we've got on you.",
        "HADDAD: Yeah, I guess.",
        "Time concluded: not specified. No further action taken.",
      ],
    },
  ],

  "reint-nigel-butt-evening": [
    {
      heading: "Further interview (voluntary) — Butt case, 2025",
      paragraphs: [
        "Interviewee: Nigel Wooley. Officers: DS H. Ferris (interviewing), DC L. Marsh (second officer). No solicitor present — not requested. Time commenced: 14:05.",
        "FERRIS: Thanks for coming in, Mr Wooley. This isn't anything to worry about — we're just following up on a few things as part of a wider review. And am I right in saying you're now retired from work?",
        "WOOLEY: Mostly, yeah, I still do a bit here and there to keep me busy. Yeah, mostly just walking the dog, see my kids from time to time. A quiet life. [Pause] So what is this about? Last time we talked things were a lot different and there are few people around here who need reminding that you never pressed charges against me for Susan's death. Now I understand that you need to do your job but I'd like to know what this is about before we continue.",
        "FERRIS: So we'll get to the point of why we're here today. What we're talking about today may have some connection to Susan's death so you, more than anyone, will know how important it is that we have an account of movements, locations, actions at the time. I want to ask you about the evening of the 22nd of May this year. Does that date mean anything to you?",
        "WOOLEY: May? Not off the top of my head, no. Should it?",
        "FERRIS: Perhaps it would be helpful if we went through your routine to see if you can remember what you were doing. How does Nigel's day start?",
        "WOOLEY: Erm, I get up at about 7, read emails and the news in bed, get out to walk the dog around 8, 8:30 if it's a slow morning. Normally on the marshes. I might stop off somewhere in the Piazza for a coffee and a croissant or something at around 9:30 or 10. Then I'm back at home. I do adult learning on Mondays and Wednesdays in the day so if it's one of those days I'll take the bus to Dagenham to do that. I'm learning art history. 12 till 3, at Dagenham College. So I do that but if it's another day I'll be at home most of the day. If I've got bits in for lunch I'll eat at home, if not I'll go to the shops — the co-op in Featherton, or the big Tesco by Critchley if I need to. So after lunch I'd maybe do some studying or listen to a podcast. If I've arranged it I'd talk to one of my daughters. Then at around 6 I'll take the dog out again, to the marshes, and if we get far enough I might go to the Red Lion on the other side there or I'll just come back. I'll probably pour myself a glass of wine when I get back, watch TV, watch the news and go to bed at around 10 or 11.",
        "FERRIS: Ok, thank you. So back around 7 or 8? So you walk the dog every day?",
        "WOOLEY: Sorry, yep twice a day.",
        "FERRIS: So it's very reasonable to think that around 5pm on the 22nd May, you would be heading towards the marshes?",
        "WOOLEY: Yes, it's very rare I don't. I don't like going towards Critchley because it's all roads. I might go there on a weekend but 9 times out of 10 it's the marshes.",
        "FERRIS: Which route do you take? Do you go by Boresfield at all?",
        "WOOLEY: No, never. Haven't set foot on that estate since Susan died — can't face it, if I'm honest. I go the other way round, round Featherton and down toward the marsh from that side.",
        "FERRIS: So I'd like you to think really hard about that night of the 22nd. Is there anyone you saw along the way, or in the marshes that struck you as strange or out of place? Any unusual cars or motor vehicles around?",
        "WOOLEY: I have no idea. I can't think of anything I've seen that's struck me as strange. I don't tend to see people along that way that I go, and the marsh is normally empty in the evenings until you get to the other side. I've seen kids hanging around up to whatever once or twice? Nothing I'd describe as strange. Just kids from the estate. I don't tend to hang around when they're there. And on that night I can't really recall much.",
        "FERRIS: Ok, if I told you this was the night that Sara Butt went missing, would that help you think about anything more clearly?",
        "WOOLEY: Sara Butt? What, the woman who they found in the marsh? Christ, so that's what this is about. Look, that was terrible. [pause] Am I being treated as a suspect now for Christ's sake?",
        "FERRIS: No Nigel, we're just trying to rule you out and to see if you know anything. We know you were in the area at a time that overlaps with her going missing, so I'm just wondering if you saw anything or can tell me anything more about that night.",
        "WOOLEY: I don't understand this. I know you have to do your job and I understand why you pulled me in before. I didn't give the best account of myself and I regret that. But what on earth do you want from me now. I have enough shit from people who still think I killed Susan, now I'm being painted as some serial killer. I didn't do it. I walked the dog and went home.",
        "FERRIS: Nigel, we just need your honest account. We are not charging you with anything, and you know that you don't have to answer and can leave at any time. Are you sure that you went to the marshes and came straight back?",
        "WOOLEY: Yes, I'm sure. I didn't realise I was a suspect in a murder case! I went out around 6 or 7. It could have been 7, when it's milder out I leave it a bit later sometimes and I think that was quite a mild evening. That's all I remember. I didn't see anyone, I walked my normal route from Featherton to the marshes, walked Missy, and came home. You can verify that with the concierge.",
        "FERRIS: Did you know Sara Butt at all? She worked in the Piazza, you wouldn't have seen her there at all?",
        "WOOLEY: No. Not to my knowledge.",
        "FERRIS: Ok, thank you Nigel. We will be able to verify all that. If there's nothing else you want to add to your account then we can leave it there. If you remember anything else you have my contact details, ok?",
        "WOOLEY: Yeah. Look you said you thought this was connected to Susan in some way?",
        "FERRIS: I can't say a lot but we are reviewing a few cases as part of this investigation and that's one of them.",
        "WOOLEY: I sincerely hope you get them.",
        "Time concluded: not specified. No further action taken. Nigel has no connection to Sara Butt and has never encountered Burgess.",
      ],
    },
  ],

  "homeowner-witness-wooley": [
    {
      heading: "Witness interview, case review (2025)",
      paragraphs: [
        "Witness: [homeowner], boiler serviced by M. Burgess on 6 January 2022, address adjoining Susan Wooley's street.",
        "INTERVIEWER: Thank you for speaking with us. I know this was a long time ago — take your time. Can you tell us anything about the visit itself?",
        "WITNESS: It's strange, isn't it, being asked about a boiler man three years on. I wouldn't have thought about it again if you hadn't asked. Honestly, most of it's gone. I couldn't tell you what time he arrived, whether he was quick or slow, any of that. But there's one thing that's stuck with me, and I don't know why it has, except that it was odd at the time.",
        "INTERVIEWER: Go on.",
        "WITNESS: He seemed off. Sweating more than the job should account for, short with me when I asked how it was going — not rude exactly, just clipped. And I remember going in to see how he was getting on, and he'd sort of jumped, and pulled his toolbox back out of sight, like he didn't want me looking in it. Then he started going on about a valve needing replacing, but it felt like he was covering for something. I didn't think anything of it at the time — you don't, do you, with a tradesman having a bad day. It's only looking back now, knowing what I know, that it seems like more than that.",
        "INTERVIEWER: Do you remember roughly what time this was?",
        "WITNESS: Afternoon into evening, I think. I couldn't give you an hour with any confidence, not after this long.",
      ],
    },
  ],

  "interim-interview-burgess": [
    {
      heading: "Voluntary interview under caution — interim interview, Butt case, 2025",
      paragraphs: [
        "Interviewee: Martin Burgess. Location: Hollenbourne Police Station, Interview Room 2. Officers: DS H. Ferris (interviewing), DC L. Marsh (second officer). Mr Burgess was offered a solicitor and declined. Time commenced: 11:20.",
        "FERRIS: This interview's being recorded, Martin. You're here voluntarily, but I do need to caution you — you don't have to say anything, but it may harm your defence if you don't mention, when questioned, something you later rely on in court. Anything you do say may be given in evidence. Understood?",
        "BURGESS: [pause] Yeah. I understand.",
        "FERRIS: You've been offered a solicitor.",
        "BURGESS: Don't need one. Already told the other officer that this morning, when you lot were going through my van. [short laugh, no humour in it] Not like I had a lot of choice, was there. You've had my van since eight this morning. Bit hard to say no after that.",
        "FERRIS: You were free to decline this interview specifically, Martin. That hasn't changed. We executed a warrant on your van this morning. I want to talk to you about what was found. There's a spanner in your kit that's noticeably cleaner than the rest of the set. It's being compared against wound patterns from two other cases.",
        "BURGESS: It probably got dirty so I cleaned it.",
        "FERRIS: It's the difference between that one and the rest of the set that's of interest. Why that one and not the others?",
        "BURGESS: [pause] I don't know what you want me to say to that. I use my tools for work. Some get more wear than others, depending what jobs I've had on. Doesn't mean anything. If it's the one I'm thinking about, it got a load of lubricant on the handle which is hard to get off without properly soaking it. Then if you leave it wet it'll get rusty so I had to give it a good wipe off.",
        "FERRIS: Forensic comparison has already found a matching tool-mark signature across two unsolved cases — Geoff Mason, 2019, and Susan Wooley, 2022. Both bludgeoned with an object consistent with an adjustable spanner.",
        "BURGESS: [long pause] I've given you the reason. I've got nothing to do with that.",
        "FERRIS: You knew Geoff Mason. You did a job at his property the day he died.",
        "BURGESS: [quiet] I told you lot that years ago. I liked the old guy. I've not hidden anything.",
        "FERRIS: Did you know Susan Wooley?",
        "BURGESS: [pause] No. Never heard of her.",
        "FERRIS: You serviced a boiler on her street in January 2022. Harrison Road.",
        "BURGESS: [pause] In Boresfield? Yeah I'm probably down that way every other week. Shitty houses and old shitty boilers. What do you want? I can't help it if some nutjob does something awful near a boiler I've serviced.",
        "FERRIS: True. But I want to ask you plainly, Martin — is there any reason a spanner from your kit would carry a tool-mark match to either of those wound patterns?",
        "BURGESS: [long pause] No. I don't know why it would. I've never hurt anyone in my life.",
        "FERRIS: Well that's not strictly true, Martin, is it?",
        "BURGESS: I was barely 20 when that went down and it was nothing. I didn't realise that something I was acquitted for when I was a kid was going to make me a murder suspect.",
        "FERRIS: Ok Martin. I think we'll leave it there for today. You're free to go — your van will be returned once the examination's complete, and we may need to speak to you again.",
        "BURGESS: [pause] How long's that going to take? I need the van for work.",
        "FERRIS: I can't give you a timeframe today. We normally have them back over to you within the week.",
        "BURGESS: [standing, quiet, controlled again] Quick as you can please.",
        "Time concluded: not specified. No arrest, no admission, nothing conclusive either way.",
      ],
    },
  ],

  "endgame-arrest-burgess-butt": [
    {
      heading: "Arrest interview, Butt case, 2025 — the endgame confrontation",
      paragraphs: [
        "Interviewee: Martin Burgess. Location: Hollenbourne Police Station, Interview Room 1. Officers: DS H. Ferris (interviewing), DC L. Marsh (second officer). Mr Burgess was offered a solicitor and declined. Time commenced: 09:40.",
        "FERRIS: This interview is being recorded. Mr Burgess, you've been arrested in connection with the death of Sara Butt, and I need to caution you. You do not have to say anything, but it may harm your defence if you do not mention, when questioned, something which you later rely on in court. Anything you do say may be given in evidence. Do you understand?",
        "BURGESS: Yeah. I understand. Yeah, I'm happy to help you out.",
        "FERRIS: Ok, so we spoke a few years back in 2019 after the death of Geoff Mason.",
        "BURGESS: Yeah, still haven't got the bloke I suppose? I hadn't heard anything about it. Alright, I hope you get them. He was a nice bloke, it was horrible what happened to him. Seems like there's a lot of that round here though. But this isn't about Geoff I assume?",
        "FERRIS: No, I'll tell you what we're interested in today but, first, can you talk me through your evening on the 22nd of May? Start from when you finished work.",
        "BURGESS: 22nd May? It's a few months ago, I don't know if I remember that day exactly. I might need to look at my calendar for that.",
        "FERRIS: Ok, so we've had a little look. Would it help if I said that you'd worked in Romford and Billericay that day and then left to go out in the evening?",
        "BURGESS: [pause] Yeah okay. Rings a bell. I think that Romford job was a real nightmare. I don't remember the Billericay one — if I don't remember it, probably more routine. On a good day I'll be back home around 5:30. Probably stayed at home. Made some dinner, watched tv.",
        "FERRIS: Can I ask you to really think back.",
        "BURGESS: Alright, I dunno, did I go for a walk or something? Look, you tell me, I don't remember it, you clearly have more information than me.",
        "FERRIS: You left your flat and took a bus, do you remember where you were going?",
        "BURGESS: I took a bus… I really can't remember.",
        "FERRIS: What I've got here is that you stepped onto the 102 bus at 8:52.",
        "BURGESS: [pause] I think I was coming here to Hollenbourne now that I think about it. Can't remember, maybe shopping or seeing someone? Yeah I go to some of the shops in the new bit sometimes. It's nice there. Like I say I can't remember the night really. It could have been something else to be fair. 8:50 did you say? Probably a bit late for shopping come to think of it.",
        "FERRIS: Do you have friends in Hollenbourne?",
        "BURGESS: Yeah a couple. There's a guy I work with, Dave. I could have been meeting him for a drink. If I took the bus it could have been that? So I could have a couple of pints and not worry about driving.",
        "FERRIS: Okay, could you give us Dave's details?",
        "BURGESS: Erm, I don't have his number. I think he lives in North Hollenbourne, the nice bit. I dunno which road. [pause] Firth I think. I'm not sure. [pause] No, I don't have it, sorry. Erm, I use facebook messenger. Just ping him a message and meet at 7 or whatever. [silence] Like I say, I'm not sure if that's what I did. I'm just trying to think. No, I haven't [been to his house], we just meet at the pub occasionally. Moan about work, you know?",
        "FERRIS: Okay, do you remember what you were wearing that evening? Do you own a puffer jacket? Dark, with a hood?",
        "BURGESS: No, couldn't tell you. I've got dark coats with hoods. Not sure about a puffer jacket. It's possible, I've got a lot of coats.",
        "FERRIS: Alright. I want to ask you about your phone. Did you have it with you that evening?",
        "BURGESS: Yeah, should have done. Don't see why I wouldn't have brought it with me.",
        "FERRIS: Ok, thank you. So you said you never visited Dave's house. Is there another reason why you would have been in the North Hollenbourne area?",
        "BURGESS: I don't think I was.",
        "FERRIS: Well we have your phone's movements with cell site data on that night and it suggests you didn't go through Featherton but went via the high street to the North Hollenbourne area. We also have footage of someone in a dark puffer jacket walking through that area at a time that matches your phone's movements. It would have been about half an hour after you got off the bus in Critchley. Is there anyone else you might have been visiting that night or any other reason why you would have been there?",
        "BURGESS: I really don't know I don't think I went that way. Are you sure that's me in the footage?",
        "FERRIS: No we're not totally sure but with everything else it seems reasonable to assume it is. Same height, same build.",
        "BURGESS: I've got no idea. I don't think that was me. I dunno about the phone. I've only ever been up that way for work.",
        "FERRIS: We've got CCTV from Hollenbourne high street, and separately a doorbell camera on Paget Street in North Hollenbourne, both from that evening. Same build, same coat, moving on foot toward the marshes, around 9:45. Did you go to the marshes that night Martin?",
        "BURGESS: No.",
        "FERRIS: What's interesting is the route. The most obvious way through that area is straight through the Featherton piazza — well-lit, heavily covered by cameras. Whoever this is goes the long way round, through residential streets with a lot less coverage.",
        "BURGESS: [pause] I don't know what you're suggesting. I wasn't there, I didn't go to the marshes.",
        "FERRIS: Are you sure Martin? You said to start off with you didn't remember that night, but we have quite a clear image of your movements and you can't explain them. Are you sure you don't remember?",
        "BURGESS: I don't remember! Look if you're sure I was there then maybe I was in the north part, I don't remember, but if you're sure I were there than I probably was. I don't go to the marshes, I don't even live round here.",
        "FERRIS: Can you think of any reason someone might specifically avoid the best-covered route through town, if they had nothing to hide?",
        "BURGESS: [pause] No idea. Maybe they just live that way. Not everyone plans their walk round CCTV, do they.",
        "FERRIS: No. Most people don't think about it at all. Alright — I want to change tack for a moment. Do you know why Sara Butt died the way she did?",
        "BURGESS: [pause] No. I mean — you hear things, don't you. About what goes on round the estates. Wouldn't surprise me if it's connected to all that. County lines stuff. That's usually what it comes down to round here, isn't it.",
        "FERRIS: [pause] You've said something very close to that to me before, Martin. Word for word, almost.",
        "BURGESS: [pause] Don't think I have.",
        "FERRIS: 2019. Geoff Mason. I interviewed you myself — you told me then that you thought it was probably drugs, kids, that sort of thing. Almost exactly what you've just said to me now, about a different person, six years apart.",
        "BURGESS: [silence] [long pause] It's just — it's what people say round here, isn't it. Everyone says the same thing about this town. Doesn't mean anything.",
        "FERRIS: Maybe not. I want to talk to you properly about Geoff Mason now, and about Susan Wooley. Both unsolved. Both killed the same way — repeated blows from a blunt object.",
        "BURGESS: I serviced Geoff's boiler. Fair enough, you have to ask questions when someone dies like that but this is ridiculous. I have no idea who Susan Wooley is, I never met her or Sara Butt.",
        "FERRIS: What about Carl Porterhouse?",
        "BURGESS: Who? Never heard of him.",
        "FERRIS: A recent forensic comparison of both cases — Mason and Wooley — found the same tool-mark signature in each. Two flat, parallel impact surfaces, evenly spaced across multiple wounds, in both victims. Consistent with an adjustable spanner. You're a gas engineer, Martin. You carry spanners for a living.",
        "BURGESS: [silence, doesn't respond immediately] [quiet] So does half the trade. That's not evidence of anything.",
        "FERRIS: On its own, no. We also traced a vehicle seen near the Mason scene in 2019 — a dark 4x4. At the time it was registered to your late father. It's since been re-registered to your mother, Patricia.",
        "BURGESS: [very long pause] That's my mum's car. Doesn't mean I had it that night. She drives it herself.",
        "FERRIS: Did you borrow it, that October? Were you in the habit of borrowing her car?",
        "BURGESS: [pause] I don't remember. That's six years ago. I couldn't tell you what car I borrowed six years ago. No. [pause] I don't know, I don't remember ever borrowing it!",
        "FERRIS: We searched your van three weeks ago, Martin, under warrant. There's a spanner in your kit that's noticeably cleaner than the rest of the set — you'll remember we discussed it. It's since been examined against the wound pattern from both cases. Do you want to tell me anything about that spanner?",
        "BURGESS: [silence; when he finally speaks, his voice has changed — quieter, none of the earlier composure left in it] No comment.",
        "FERRIS: Martin, this is your opportunity to tell us how it happened. I think, generously, 10 percent of what you've told us today is false. And we know it, Martin. We don't ask questions that we don't know the answers to.",
        "BURGESS: [pause] No comment.",
        "FERRIS: Tell us if we've missed something, Martin. Tell us if there's a reason you were walking to the marshes on the 22nd. Tell us if there's a reason one of your spanners has been meticulously cleaned and the others are dirty? If there's a reason, Martin, this is your chance. [pause] What happened, Martin?",
        "BURGESS: [pause] I want a solicitor.",
        "FERRIS: That's your right. This interview is suspended at 10:47 to allow Mr Burgess to obtain legal advice.",
        "Time suspended: 10:47. No confession obtained.",
      ],
    },
  ],

  "riverbank-liaison-swayne": [
    {
      heading: "Operation Riverbank — interview under caution, 2024",
      paragraphs: [
        "ESSEX & EAST LONDON BOUNDARY ORGANISED CRIME UNIT. Interviewee: Colin Swayne. Officers: DC S. Whitlock (interviewing), DC M. Farrow (second officer). Mr Swayne was offered a solicitor and declined.",
        "WHITLOCK: This interview's being recorded, Colin. You're not under arrest today — this is part of a wider operation we're running, looking at the network operating in and around Boresfield. Not about any one thing you've done personally. We know your flat's been used to store and sell drugs for some time now. I want to be straight with you — we're not here to charge you over that today. What we're trying to build is a proper picture of how this actually works. Start with how it started, for you.",
        "SWAYNE: [long pause] Back in '19. Just got the flat, hadn't been there long. Two lads came round one evening. Didn't really introduce themselves properly, just — made it clear they needed somewhere to work from, and that I was going to be that somewhere.",
        "WHITLOCK: Did they give you a choice?",
        "SWAYNE: [short laugh, no humour in it] Not really, no. Not in so many words. Nobody threatened me outright, if that's what you're asking. It's more — you understand what's being said without them having to say it.",
        "WHITLOCK: What did you get out of it?",
        "SWAYNE: Bit of money. Gear, when I wanted it, which was most of the time back then. Left alone, long as I didn't cause trouble or ask questions.",
        "WHITLOCK: Has that changed over the years? More of them coming and going, longer hours, anything like that?",
        "SWAYNE: [pause] Bit, yeah. Started as a couple of evenings a week. By last year it was most days. You stop noticing after a while. It's just what the flat is now.",
        "WHITLOCK: Kato and Reece — that's who came to you originally?",
        "SWAYNE: [pause] Yeah. Them.",
        "WHITLOCK: Were you the first place they tried in the area, do you know? Or had they already got somewhere else lined up before you?",
        "SWAYNE: [long pause] Don't know that they had anywhere lined up exactly. I do know — [stops] I know they'd tried someone else first. Before me.",
        "WHITLOCK: Can you tell me who?",
        "SWAYNE: [quiet] Old boy, up by the marsh. Never got a name off them, they just called him \"the old boy.\" Wasn't there for it myself, I'm only telling you what they said.",
        "WHITLOCK: What did they say happened?",
        "SWAYNE: Laughed about it, actually. Like it was a joke. Said they'd gone round, made him the same offer they made me, and he'd told them where to go. In no uncertain terms, from how they told it. Had more nerve than they expected from an old fella on his own. Wasn't going to happen, so they moved on. Come to me not long after.",
        "WHITLOCK: Roughly when was this — the approach to him, I mean?",
        "SWAYNE: Around the same time as me getting the flat. Maybe a few weeks before. Couldn't give you an exact date.",
        "WHITLOCK: Does the name Geoff Mason mean anything to you?",
        "SWAYNE: [pause] Should it?",
        "WHITLOCK: He was found dead later that same year. October.",
        "SWAYNE: [long silence] ...That's him? The old boy from the marsh?",
        "WHITLOCK: We believe so, yes.",
        "SWAYNE: [quiet, shaken] Didn't know that. God. I didn't — nobody said anything about that being the same bloke. I just thought — [stops, doesn't finish] Was he — did they have anything to do with that? Kato and that lot?",
        "WHITLOCK: That's not something I can go into with you today, Colin. I do want to thank you for telling me what you have. Is there anything else from around that time you think might be relevant — anything else they mentioned, other addresses, other names?",
        "SWAYNE: [pause] Not that I can think of. That's the only one I ever heard about.",
        "WHITLOCK: Alright. Thank you, Colin. That's everything for today.",
        "Time concluded: not specified. No further action taken on the Mason reference — outside this unit's remit, and nothing formally flags it for the Porterhouse murder team. Swayne's shock is genuine: he never connected the men who approached Mason to Mason's later death, so there was never anything for him to volunteer to anyone else.",
      ],
    },
  ],

  // -----------------------------------------------------------------------
  // Cell site & ANPR analyst reports — hollenbourne-cell-site-data.md
  // -----------------------------------------------------------------------
  "cellsite-burgess-wooley": [
    {
      heading: "Communications Data — Cell Site Analysis",
      paragraphs: [
        "Subject: Martin Burgess. Period requested: 6 January 2022, 14:00–18:00. Requesting officer: Case review team.",
        "Finding: The subject's device connects to a cell sector covering the booked job's street and the adjoining street (Susan Wooley's address falls within the same sector) from 15:14 continuously through to 16:51, at which point it moves to a sector consistent with travel toward Featherton — his next logged appointment. No second booking is recorded at any address within this sector for the period after the first job's expected completion.",
        "Investigative relevance: A routine boiler service of the type logged typically runs 30–45 minutes. The device remains within the same sector for approximately 95 minutes — around 45–50 minutes longer than the booked job alone would account for, with no second job logged to explain the remainder. This is consistent with, and independently corroborates, the subject's own later account (2025 arrest interview) of an unbooked visit of roughly 35 minutes at an adjoining address that afternoon. The sector itself is not narrow enough to confirm presence at any single address — this finding establishes an unexplained gap in his account, not a location.",
        "This is the single most valuable new addition to the Wooley case specifically: the only one of Burgess's three killings with no independent movement-evidence chain until now. Mason has the vehicle/traffic-camera route; Butt has the bus/CCTV/doorbell route; Wooley had nothing beyond Ferris's own unease and the (now-filed) homeowner witness. This closes that gap without over-claiming precision. Cell site data shows which mast/sector a device connected to, not a precise GPS location — it corroborates or complicates an account, it doesn't independently prove presence at an exact address.",
      ],
    },
  ],

  "cellsite-burgess-mason": [
    {
      heading: "Communications Data — Cell Site Analysis",
      paragraphs: [
        "Subject: Martin Burgess. Period requested: 8 October 2019, 15:00–22:00. Requesting officer: Case review team.",
        "Finding: The device enters the Boresfield sector via Chertsey Street at approximately 15:18, consistent with travel to the booked appointment. It connects to the sector covering Geoff Mason's street from 15:31 to 16:20, matching the appointment itself, before moving to a sector consistent with Harrison Road at approximately 16:33 — a different route out of the estate than the one used to enter it. No cell activity is recorded for the device that evening.",
        "Investigative relevance: The full afternoon picture — arrival, appointment, and a departure route that doesn't retrace the approach — is confirming rather than new on its own, but it establishes a normal, complete pattern of movement for a routine job, which is exactly the baseline the evening gap stands out against. That gap is the more interesting finding: consistent with the established account, he doesn't have his phone with him for the return trip to the marsh, whether by deliberate precaution or simple incidental caution — it isn't established either way, and doesn't need to be. That evening window is corroborated instead by the traffic camera, ANPR, and doorbell canvass evidence already on file, none of which depend on the phone at all.",
        "Worth using this deliberately with students: a genuine gap in one evidence type doesn't undermine what the others independently establish — investigations lean on multiple data sources precisely because no single one covers everything, and a team that expected cell data to confirm every other finding needs to learn that lesson somewhere.",
      ],
    },
  ],

  "cellsite-burgess-butt": [
    {
      heading: "Communications Data — Cell Site Analysis",
      paragraphs: [
        "Subject: Martin Burgess. Period requested: 22 May 2025, 21:00–23:00. Requesting officer: Case review team.",
        "Finding: The device connects to the sector covering the Critchley estate at 20:48, consistent with the bus journey already on file (contactless boarding, 8:52pm). It moves through the high street sector and into the North-Hollenbourne sector — consistent with Paget Street — by 21:45, then reaches the sector covering the Hollen Marsh southern approach by approximately 22:30, remaining there until the connection is lost (consistent with the device being switched off or entering an area of poor coverage) at 22:58.",
        "Investigative relevance: Independently corroborates the bus operator CCTV, high street CCTV, and Paget Street doorbell camera sightings already on file, all three timestamped separately and never cross-referenced against telecoms data until now. Again, a confirming piece — genuinely valuable stacked on top of the existing chain, not a substitute for it.",
      ],
    },
  ],

  "cellsite-nigel-butt": [
    {
      heading: "Communications Data — Cell Site Analysis",
      paragraphs: [
        "Subject: Nigel Wooley. Period requested: 22 May 2025, 18:00–23:00. Requesting officer: Case review team.",
        "Finding: The device remains within the Featherton sector from 18:00, moving briefly to the sector covering the marsh's northern approach between 19:40 and 20:05, before returning to and remaining within the Featherton sector for the rest of the evening — well clear of Sara Butt's own confirmed movements, which begin with her 22:49 WhatsApp message near the Boresfield bus stop.",
        "Investigative relevance: Independently corroborates Nigel's own account of an early-evening dog walk near the marsh's northern approach, well before the attack, at a different time and via a different cell path than Burgess's route that same night. This is exonerating evidence, and worth presenting to students as exactly that: the same tool that builds a case against Burgess clears Nigel with equal confidence, once actually used. A useful corrective to the instinct that more data always points toward guilt.",
      ],
    },
  ],

  "cellsite-swayne-porterhouse": [
    {
      heading: "Communications Data — Cell Site Analysis",
      paragraphs: [
        "Subject: Colin Swayne. Period requested: 29 May 2023, 19:00–23:00. Requesting officer: Case review team.",
        "Finding: The device is stationary within a single sector covering both the subject's own address and Carl Porterhouse's address (the two properties fall within the same sector) from 20:41 continuously through to 22:15, at which point the connection becomes intermittent for the remainder of the recorded period.",
        "Investigative relevance: Over ninety minutes' continuous presence in the shared sector, consistent with Swayne's eventual admission of a visit \"over an hour\" long — and starkly inconsistent with his initial denial of ever having left home that evening. This data was requestable from the earliest days of the original 2023 investigation and was never pulled: once Swayne's own account settled into something the investigating team found plausible, nobody thought to independently check it against telecoms data. A clean example of the case's recurring pattern — not a cover-up, just nobody joining data that was sitting there the whole time.",
      ],
    },
  ],

  "anpr-burgess-vehicle-history": [
    {
      heading: "ANPR data request — case review",
      paragraphs: [
        "Vehicle: KN58 TVP (dark 4x4), registered to Patricia Burgess. Period requested: 1 October 2019 – 31 May 2025 (spanning all three relevant dates).",
        "Finding: The vehicle is picked up by ANPR cameras on the approach roads to Hollen Marsh at 9:11pm and 9:54pm on 8 October 2019 — independently corroborating the local authority traffic camera sighting already on file (9:14pm/9:52pm), two separate camera networks reaching the same conclusion without ever having been cross-checked against each other until this review. The same plate returns no ANPR hits in the vicinity of Susan Wooley's address on 6 January 2022, or near Hollen Marsh or the Boresfield/Critchley area on 22 May 2025.",
        "Investigative relevance: The Mason-night result is confirming, not new. The absence of any hit on the other two dates is the genuinely useful finding here: it's consistent with, and corroborates, Burgess's already-established methods for those two killings — walking from a neighbouring job for Wooley, bus and on foot for Butt — rather than driving. A negative result from a properly targeted search is still evidence; it closes off an alternative theory (that he drove on those nights too) as cleanly as a positive hit confirms one.",
      ],
    },
  ],

  "anpr-sweep-hollen-marsh-2019": [
    {
      heading: "ANPR data request — case review",
      paragraphs: [
        "Area: all camera-covered approach roads to Hollen Marsh. Period requested: 8 October 2019, 21:00–22:00.",
        "Finding: Four vehicles pass through camera coverage in the requested window. One is the dark 4x4 registered to Patricia Burgess. The other three: a taxi, later confirmed (via the operator's own job log) to be en route to an unrelated fare in North-Hollenbourne; a resident's car, registered to an address on the approach road itself — a normal return home, nothing further to it; and a delivery van, confirmed against the driver's own employer records as working a scheduled round that evening, unconnected to any address relevant to this case.",
        "Investigative relevance: Deliberately included as investigative texture rather than a fourth lead: an unfiltered sweep returns noise as well as signal, and every one of these three would need to be run down and eliminated in a real investigation before anyone could be confident the fourth was the one that mattered. Worth using this to make an explicit point to students about cost — chasing all three unconnected vehicles individually would be expensive in points for zero investigative return, exactly the kind of judgement call a real SIO has to make constantly and mostly invisibly.",
      ],
    },
  ],

  "anpr-haddad-marsh-road": [
    {
      heading: "ANPR data request — case review",
      paragraphs: [
        "Vehicle: [registration], registered to Khalid Haddad. Period requested: 6 January 2022, 17:30–18:30.",
        "Finding: The vehicle is picked up by an ANPR camera at the northern end of Marsh Road at 18:04, and again heading back onto Chertsey Street at 18:16 — closely matching the timeline already established through his employer's delivery-app data and his own account in interview.",
        "Investigative relevance: Worth being honest about what this does and doesn't add: it doesn't tell a team anything new about where Haddad was — the app data already nailed that down precisely. What it does do is confirm it from a completely independent institutional source, the same way the Mason-night traffic camera and ANPR results confirm each other. Two silos, employer data and the police's own camera network, reaching the same conclusion without ever having been checked against each other. A small, honest demonstration that corroboration has value even when it isn't discovery.",
      ],
    },
  ],

  "anpr-sweep-featherton-2022": [
    {
      heading: "ANPR data request — case review",
      paragraphs: [
        "Area: Featherton, camera-covered roads only. Period requested: 6 January 2022, 18:10–18:20.",
        "Finding: Three vehicles pass through camera coverage in the requested window, besides Haddad's own: a resident's car, registered to a Featherton address, confirmed as a normal return home; a delivery van from a different, unrelated courier firm, working a separate scheduled round; and one vehicle whose plate returns no match on the DVLA database at all — inconclusive. Could be a data-capture error (a common, mundane cause), a cloned or false plate, or simply a vehicle passing through moments outside the requested window and misattributed. Not resolvable from ANPR data alone.",
        "Investigative relevance: The unmatched plate is the interesting result here, and deliberately left unresolved rather than quietly explained away. It's consistent with — though it doesn't prove — the established picture of a low-level, deniable operation that survives specifically by being hard to pin down through ordinary channels; the same reason Kato and Reece themselves stay unidentifiable through any other evidence in this case. Worth resisting the urge to hand students a clean answer here: real organised crime investigation runs into exactly this kind of dead end constantly, and an unmatched plate is a realistic place for the trail to simply stop.",
      ],
    },
  ],

  // -----------------------------------------------------------------------
  // Procedural documents — hollenbourne-procedural-documents.md
  // -----------------------------------------------------------------------
  "holly-creagan-statement": [
    {
      heading: "Witness statement — Swayne alibi, case review, 2025 (Criminal Justice Act 1967, s.9)",
      paragraphs: [
        "Statement of: Holly Creagan. Address: Folkestone Road, Boresfield. This statement, consisting of one page, is true to the best of my knowledge and belief.",
        "\"I've known Colin a few years now, since round when he moved onto the estate. We're not close exactly, but he comes round mine some evenings and we'll use together — that's just how we know each other, really, more than being proper friends.",
        "I was asked about a night back in May, whether he was round at mine. I said he probably was, since he's round often enough, but I couldn't tell you for certain it was that exact date. Evenings like that blend into each other for me, if I'm honest — I couldn't swear to one night over another, not weeks later. It might have been that night, might have been a night or two either side of it. I don't keep a diary or anything like that.",
        "Nobody's told me what this is actually about and I haven't asked. I've just answered what I've been asked as best I can remember it, which isn't as much as I'd like it to be.\"",
        "Signed: H. Creagan.",
        "No further action taken on this statement alone. Leaves Swayne's whereabouts on the Butt evening genuinely unresolved — neither confirmed nor contradicted — rather than closing the question either way. Holly was not told the specific date connects to Sara Butt's death, and didn't ask; her account is genuinely uncomplicated rather than guarded.",
      ],
    },
  ],

  "haddad-record-summary": [
    {
      heading: "Historical record summary — subject: Khalid Haddad",
      paragraphs: [
        "Requested by: Case review team.",
        "PNC/CRIS summary: 2018 — arrested during a police operation targeting a county lines route operating through Hornchurch. Found at a property used to store product, alongside two older men, both of whom had prior drugs convictions. A duty solicitor present at first interview raised concern regarding potential exploitation, citing the subject's age (18), immigration history (arrived as an unaccompanied asylum claimant, 2015), and absence of any prior record. An NRM referral was submitted prior to charge. Case status: discontinued — a Section 45 Modern Slavery Act 2015 defence was accepted, the offence found to be a direct consequence of exploitation. No conviction recorded.",
        "NRM outcome (Home Office, Single Competent Authority): Reasonable grounds decision — positive (potential victim of modern slavery/criminal exploitation). Conclusive grounds decision — positive, confirmed some months later.",
        "Relevance to case review: this is a formal, positive finding by the Home Office's own competent authority — not a character reference, not a plea in mitigation, an official determination that Haddad was a victim of criminal exploitation as a minor-to-young-adult. Anyone reading his file cold, starting from the 2023 arrest and the \"no comment\" interview, would reasonably read him as someone with a drugs-adjacent record who won't cooperate. This record inverts that reading entirely, and it was sitting in the system the whole time — nobody thought to pull it until this review.",
      ],
    },
  ],

  "phone-data-butt": [
    {
      heading: "Digital Forensics — Exhibit Report",
      paragraphs: [
        "Requested by: Case review team. Device: Sara Butt's mobile phone (recovered, see forensic recovery log). Extraction method: standard mobile device forensic extraction.",
        "Finding of note: A WhatsApp message sent from the deceased's device to a contact saved as \"Mum & Dad\" at 22:49:07 on 22 May 2025, reading: \"back in 10\". GPS metadata attached to the message places the device within the expected range of the bus stop on the southern edge of Boresfield at the time of sending. No further outgoing activity from the device after this timestamp. The device's own local clock is consistent with network time at the point of extraction, giving no reason to doubt the accuracy of the timestamp.",
        "Investigative relevance: Primarily useful for timeline construction rather than direct identification of any suspect — establishes with confidence the point at which Sara was both alive and in the immediate vicinity of the bus stop, and narrows the window in which the attack must have taken place to the minutes immediately following. Cross-references cleanly with the bus operator's own boarding timestamp (8:52pm) and the Paget Street doorbell camera sighting (approximately 9:45pm) already on file — all three independently timestamped records are consistent with a single continuous account of the evening, though none of them were compared against each other until this review.",
      ],
    },
  ],
};
